Vagrant.configure("2") do |config|
  config.vm.box = "wesmcclure/ubuntu1404-docker"
  config.vm.provision "shell", path: "install.consul.sh", privileged: false

  config.vm.define "consul-server" do |cs|
    cs.vm.hostname = "consul-server"
    cs.vm.network "private_network", ip: "172.20.20.31"
  end

  config.vm.define "node-a" do |cs|
    cs.vm.hostname = "node-a"
    cs.vm.network "private_network", ip: "172.20.20.21"
  end

  config.vm.define "node-b" do |cs|
    cs.vm.hostname = "node-b"
    cs.vm.network "private_network", ip: "172.20.20.22"
  end

  config.vm.define "node-c" do |cs|
    cs.vm.hostname = "node-c"
    cs.vm.network "private_network", ip: "172.20.20.23"
  end

  config.vm.define "node-d" do |cs|
    cs.vm.hostname = "node-d"
    cs.vm.network "private_network", ip: "172.20.20.24"
  end
end
